name: 'generate chart report'
on:
  issues:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  generate-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{secrets.TOKEN}}
      - uses: minuth/quickchart-report@main
        with:
          token: ${{secrets.TOKEN}}
