name: 'report'
on: # rebuild any PRs and main branch changes
  issues:

jobs:
  get-report: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: minuth/report-action@main
